### ISSUE TITLE
Please provide `Value` instances for tuples

### ISSUE THREAD

**Issue by hvr** [lpsmith/json-builder#1]
This would be convenient as it provides the obvious serialization for tuples as non-homogenous JSON Arrays.

An example for a 2-tuple is shown below

``` haskell
instance (Value a, Value b) => Value (a,b) where
    toJson (a,b) = toJson [toJson a,toJson b]
```

**Comment by lpsmith** [comment]
Ok, done.  I included up to 4-tuples.   Perhaps I should change the rendering of () to be a zero-element array, which is what Aeson does.
